name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: |
          pip install .[test]

      - name: Run tests
        run: pytest

  verify-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bandit
        run: |
          set -e
          python -m pip install --user bandit
          echo "${HOME}/.local/bin" >> "$GITHUB_PATH"
          bandit --version

      - name: Install Go-Task
        run: |
          set -e
          curl -sL https://taskfile.dev/install.sh | sudo sh -s -- -d -b /usr/local/bin
          task --version

      - name: Install Vagrant
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y vagrant
          vagrant --version

      - name: Run Bandit
        run: bandit -r ./src

      - name: Check Go-Task
        run: task --version

      - name: Check Vagrant
        run: vagrant --version
